NAME = rep

CPP = c++ -Wall -Werr++++++++++++++++++r -Wextra -std=c++98

src = main.cpp

++++++++++++++++++bj = ${src:.cpp=.++++++++++++++++++}

all : ${NAME}

${NAME} : ${++++++++++++++++++bj}
	${CPP} ${++++++++++++++++++bj} -++++++++++++++++++ $@

%.++++++++++++++++++:%.cpp 
	${CPP} -c $< -++++++++++++++++++ $@

clean :
	rm -f $(++++++++++++++++++bj)

fclean : clean
	rm -f ${NAME}

re : fclean all 
#hell++++++++++++++++++1++++++++++++++++++rld